# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Backward Compatibility Check"

on:
  pull_request:
  push:
    branches:
      - "[0-9]+.[0-9]+.x"

jobs:
  roave-backwards-compatibility-check:
    name: "Backward Compatibility Check"
    continue-on-error: true

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.0"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          extensions: pdo_sqlite, bcmath, intl, sodium

      - uses: ramsey/composer-install@2.1.0
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - uses: ramsey/composer-install@2.1.0
        with:
          dependency-versions: ${{ matrix.dependencies }}
          working-directory: 'tools'

      - name: "Check for BC breaks"
        run: "tools/vendor/bin/roave-backward-compatibility-check --format=github-actions --install-development-dependencies --from=origin/${{ github.base_ref }}"
