# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Benchmark"

on:
  pull_request:
  push:
    branches:
      - "[0-9]+.[0-9]+.x"

jobs:
  phpbench:
    name: "Benchmark"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.0"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          extensions: pdo_sqlite

      - name: "Checkout base"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - uses: ramsey/composer-install@2.1.0
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: "phpbench on base"
        run: "vendor/bin/phpbench run tests/Benchmark --progress=none --report=default --tag=base"

      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          clean: false

      - uses: ramsey/composer-install@2.1.0
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: "phpbench list"
        run: "vendor/bin/phpbench log"

      - name: "phpbench diff"
        run: "vendor/bin/phpbench run tests/Benchmark --progress=none --report=default --ref=base > bench.txt"

      - name: "Get Bench Result"
        id: phpbench
        run: |
          echo "::set-env name=bench::$(<bench.txt)"

      - name: "Echo for testing"
        run: |
          echo ${{ steps.phpbench.outputs.bench }}
          cat bench.txt

      - uses: actions/github-script@v6
        with:
          script: |
            // Get the existing comments.
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
            })

            // Find any comment already made by the bot.                                                                                                    
            const botComment = comments.find(comment => comment.user.id === 41898282)                                                                       
            const commentBody = `
            
            Benchmark Result:
            
            \`\`\`
            ${{ env.bench }}
            \`\`\`
            
            `;

            if (context.payload.pull_request.head.repo.full_name !== 'patchlevel/event-sourcing') {
              console.log('Not attempting to write comment on PR from fork');
            } else {
              if (botComment) {
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: botComment.id,
                  body: commentBody
                })
              } else {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.number,
                  body: commentBody
                })
              }
            }
