# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Static Analysis by PHPStan"

on:
    pull_request:
    push:
        branches:
            - "[0-9]+.[0-9]+.x"

jobs:
    static-analysis-phpstan:
        name: "Static Analysis by PHPStan"

        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                dependencies:
                    - "locked"
                php-version:
                    - "8.0"
                operating-system:
                    - "ubuntu-latest"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "pcov"
                  php-version: "${{ matrix.php-version }}"
                  ini-values: memory_limit=-1
                  extensions: pdo_sqlite, sodium

            - uses: "ramsey/composer-install@v2"
              with:
                dependency-versions: ${{ matrix.dependencies }}

            - name: "PHPStan"
              run: "vendor/bin/phpstan analyse"
